#books.genre:IT


#=================

quarkus.log.category."io.quakus".level=DEBUG
quarkus.log.category."org.agoncal".level=INFO
quarkus.banner.enabled=false

%dev.quarkus.log.console.level=DEBUG
%test.quarkus.log.console.level=TRACE
%prod.quarkus.log.console.level=SEVERE


%prod.books.genre=Information Technology
%dev.books.genre=Information Technology
%test.books.genre=IT
%staging.books.genre=crime
